service: product-service
frameworkVersion: "2"
custom:
  webpack:
    packager: yarn
    webpackConfig: webpack.config.js
    includeModules: true
plugins:
  - serverless-webpack
provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  stage: dev
  lambdaHashingVersion: 20201221
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"

functions:
  getProductsList:
    handler: src/functions/index.getProductsList
    events:
      - http:
          method: get
          path: products
          cors:
            origin: '*'

  getProductById:
    handler: src/functions/index.getProductById
    events:
      - http:
          method: get
          path: products/{id}
          cors:
            origin: '*'

