service: product-service
frameworkVersion: "2"

plugins:
  - serverless-webpack
  - serverless-openapi-documentation

custom:
  webpack:
    packager: yarn
    webpackConfig: webpack.config.js
    includeModules: true
  documentation: ${file(serverless.doc.yml):documentation}

provider:
  name: aws
  runtime: nodejs14.x
  region: ${file(env.yml):provider.REGION}
  stage: ${file(env.yml):provider.STAGE}
  lambdaHashingVersion: 20201221
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
    PG_HOST: ${file(env.yml):pg.HOST}
    PG_PORT: ${file(env.yml):pg.PORT}
    PG_DATABASE: ${file(env.yml):pg.DATABASE}
    PG_USER: ${file(env.yml):pg.USER}
    PG_PASSWORD: ${file(env.yml):pg.PASSWORD}

functions:
  getProductsList:
    handler: src/functions/index.getProductsList
    events:
      - http:
          method: get
          path: products
          cors:
            origin: "*"
          documentation: ${file(serverless.doc.yml):endpoints.getProductsList}

  getProductById:
    handler: src/functions/index.getProductById
    events:
      - http:
          method: get
          path: products/{id}
          cors:
            origin: "*"
          documentation: ${file(serverless.doc.yml):endpoints.getProductById}

  putProduct:
    handler: src/functions/index.putProduct
    events:
      - http:
          method: put
          path: products
          cors:
            origin: "*"
