export default {
  definitions: {},
  $id: "Product",
  title: "Product",
  type: "object",
  required: ["count", "description", "id", "price", "title"],
  properties: {
    count: {
      $id: "#root/count",
      title: "Count",
      type: "integer",
      examples: [3],
      default: 0,
    },
    description: {
      $id: "#root/description",
      title: "Description",
      type: "string",
      default: "",
      examples: ["iPhone 8"],
      pattern: "^.*$",
    },
    id: {
      $id: "#root/id",
      title: "Id",
      type: "string",
      default: "",
      examples: ["7567ec4b-b10c-45c5-9345-fc73c48a80a1"],
      pattern: "^.*$",
    },
    price: {
      $id: "#root/price",
      title: "Price",
      type: "integer",
      examples: [100],
      default: 0,
    },
    title: {
      $id: "#root/title",
      title: "Title",
      type: "string",
      default: "",
      examples: ["iPhone 4s"],
      pattern: "^.*$",
    },
  },
} as const
