service: authorization-service
frameworkVersion: "2"

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

custom:
  webpack:
    packager: yarn
    webpackConfig: webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs14.x
  region: ${file(env.yml):provider.REGION}
  stage: ${file(env.yml):provider.STAGE}
  lambdaHashingVersion: 20201221
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"

functions:
  basicAuthorizer :
    handler: src/functions/index.basicAuthorizer
